"""Base interface for signal sources."""

from __future__ import annotations

import abc
import datetime  # noqa: TCH003
from dataclasses import dataclass, field
from enum import StrEnum
from typing import Any


class SignalUrgency(StrEnum):
    """Signal urgency level."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


@dataclass(frozen=True)
class Signal:
    """A trading signal generated by a signal source."""

    source: str
    timestamp: datetime.datetime
    event_type: str
    data: dict[str, Any]
    relevant_series: list[str] = field(default_factory=list)
    urgency: SignalUrgency = SignalUrgency.LOW


class SignalSource(abc.ABC):
    """Abstract base class for signal sources (plugin interface)."""

    @property
    @abc.abstractmethod
    def name(self) -> str:
        """Unique name of this signal source."""

    @property
    @abc.abstractmethod
    def poll_interval_seconds(self) -> int:
        """How often this source should be polled."""

    @abc.abstractmethod
    async def initialize(self) -> None:
        """Set up the signal source (connections, state, etc.)."""

    @abc.abstractmethod
    async def poll(self) -> list[Signal]:
        """Poll for new signals. Returns list of signals detected since last poll."""

    @abc.abstractmethod
    async def teardown(self) -> None:
        """Clean up resources."""
