"""SQLAlchemy ORM models for the autotrader database."""

from __future__ import annotations

import datetime  # noqa: TCH003
from typing import Any

from sqlalchemy import (
    JSON,
    Boolean,
    DateTime,
    Float,
    Index,
    Integer,
    String,
    Text,
    func,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    """Base class for all ORM models."""

    type_annotation_map = {
        dict[str, Any]: JSON,
    }


class Order(Base):
    """Every order submitted to Kalshi (or simulated)."""

    __tablename__ = "orders"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    client_order_id: Mapped[str] = mapped_column(String(64), unique=True, index=True)
    kalshi_order_id: Mapped[str | None] = mapped_column(String(64), nullable=True, index=True)
    ticker: Mapped[str] = mapped_column(String(64), index=True)
    event_ticker: Mapped[str | None] = mapped_column(String(64), nullable=True, index=True)
    series_ticker: Mapped[str | None] = mapped_column(String(64), nullable=True)
    side: Mapped[str] = mapped_column(String(4))  # "yes" or "no"
    price_cents: Mapped[int] = mapped_column(Integer)
    quantity: Mapped[int] = mapped_column(Integer)
    filled_quantity: Mapped[int] = mapped_column(Integer, default=0)
    remaining_quantity: Mapped[int] = mapped_column(Integer, default=0)
    status: Mapped[str] = mapped_column(String(20), index=True)  # pending, resting, partial, filled, cancelled
    strategy: Mapped[str] = mapped_column(String(64), index=True)
    urgency: Mapped[str] = mapped_column(String(20))  # passive, adaptive, aggressive
    rationale: Mapped[str | None] = mapped_column(Text, nullable=True)
    is_paper: Mapped[bool] = mapped_column(Boolean, default=True)
    created_at: Mapped[datetime.datetime] = mapped_column(DateTime, server_default=func.now())
    updated_at: Mapped[datetime.datetime] = mapped_column(DateTime, server_default=func.now(), onupdate=func.now())
    filled_at: Mapped[datetime.datetime | None] = mapped_column(DateTime, nullable=True)
    cancelled_at: Mapped[datetime.datetime | None] = mapped_column(DateTime, nullable=True)

    __table_args__ = (
        Index("ix_orders_ticker_status", "ticker", "status"),
        Index("ix_orders_strategy_created", "strategy", "created_at"),
    )


class Position(Base):
    """Current positions per market."""

    __tablename__ = "positions"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    ticker: Mapped[str] = mapped_column(String(64), unique=True, index=True)
    event_ticker: Mapped[str | None] = mapped_column(String(64), nullable=True, index=True)
    series_ticker: Mapped[str | None] = mapped_column(String(64), nullable=True)
    side: Mapped[str] = mapped_column(String(4))  # "yes" or "no"
    quantity: Mapped[int] = mapped_column(Integer, default=0)
    avg_cost_cents: Mapped[float] = mapped_column(Float, default=0.0)
    total_cost_cents: Mapped[float] = mapped_column(Float, default=0.0)
    unrealized_pnl_cents: Mapped[float] = mapped_column(Float, default=0.0)
    strategy: Mapped[str] = mapped_column(String(64), index=True)
    is_paper: Mapped[bool] = mapped_column(Boolean, default=True)
    opened_at: Mapped[datetime.datetime] = mapped_column(DateTime, server_default=func.now())
    updated_at: Mapped[datetime.datetime] = mapped_column(DateTime, server_default=func.now(), onupdate=func.now())


class Fill(Base):
    """Every execution (fill) received."""

    __tablename__ = "fills"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    order_client_id: Mapped[str] = mapped_column(String(64), index=True)
    kalshi_fill_id: Mapped[str | None] = mapped_column(String(64), nullable=True, unique=True)
    ticker: Mapped[str] = mapped_column(String(64), index=True)
    side: Mapped[str] = mapped_column(String(4))
    price_cents: Mapped[int] = mapped_column(Integer)
    quantity: Mapped[int] = mapped_column(Integer)
    fee_cents: Mapped[int] = mapped_column(Integer, default=0)
    is_taker: Mapped[bool] = mapped_column(Boolean, default=True)
    is_paper: Mapped[bool] = mapped_column(Boolean, default=True)
    strategy: Mapped[str] = mapped_column(String(64))
    filled_at: Mapped[datetime.datetime] = mapped_column(DateTime, server_default=func.now())

    __table_args__ = (Index("ix_fills_ticker_filled", "ticker", "filled_at"),)


class Signal(Base):
    """Every signal generated by signal sources."""

    __tablename__ = "signals"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    source: Mapped[str] = mapped_column(String(64), index=True)
    event_type: Mapped[str] = mapped_column(String(64), index=True)
    urgency: Mapped[str] = mapped_column(String(10))
    data: Mapped[dict[str, Any]] = mapped_column(JSON, default=dict)
    relevant_series: Mapped[dict[str, Any]] = mapped_column(JSON, default=list)  # stored as JSON list
    action_taken: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime.datetime] = mapped_column(DateTime, server_default=func.now())

    __table_args__ = (Index("ix_signals_source_type", "source", "event_type"),)


class RiskEvent(Base):
    """Every risk check rejection."""

    __tablename__ = "risk_events"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    check_name: Mapped[str] = mapped_column(String(64), index=True)
    proposed_order: Mapped[dict[str, Any]] = mapped_column(JSON)
    reason: Mapped[str] = mapped_column(Text)
    created_at: Mapped[datetime.datetime] = mapped_column(DateTime, server_default=func.now())


class LeaderboardSnapshot(Base):
    """Full Arena leaderboard state at each poll."""

    __tablename__ = "leaderboard_snapshots"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    snapshot_data: Mapped[dict[str, Any]] = mapped_column(JSON)
    source_url: Mapped[str] = mapped_column(String(256))
    model_count: Mapped[int] = mapped_column(Integer, default=0)
    top_model: Mapped[str | None] = mapped_column(String(128), nullable=True)
    top_org: Mapped[str | None] = mapped_column(String(128), nullable=True)
    captured_at: Mapped[datetime.datetime] = mapped_column(DateTime, server_default=func.now(), index=True)


class DailyPnl(Base):
    """Daily P&L snapshots by strategy."""

    __tablename__ = "daily_pnl"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    date: Mapped[datetime.date] = mapped_column(DateTime, index=True)
    strategy: Mapped[str] = mapped_column(String(64), index=True)
    realized_pnl_cents: Mapped[int] = mapped_column(Integer, default=0)
    unrealized_pnl_cents: Mapped[int] = mapped_column(Integer, default=0)
    total_fees_cents: Mapped[int] = mapped_column(Integer, default=0)
    trade_count: Mapped[int] = mapped_column(Integer, default=0)
    is_paper: Mapped[bool] = mapped_column(Boolean, default=True)
    created_at: Mapped[datetime.datetime] = mapped_column(DateTime, server_default=func.now())

    __table_args__ = (Index("ix_daily_pnl_date_strategy", "date", "strategy", unique=True),)


class SystemEvent(Base):
    """System lifecycle events: startup, shutdown, errors, disconnects."""

    __tablename__ = "system_events"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    event_type: Mapped[str] = mapped_column(String(64), index=True)
    details: Mapped[dict[str, Any]] = mapped_column(JSON, default=dict)
    severity: Mapped[str] = mapped_column(String(10))  # info, warning, error, critical
    created_at: Mapped[datetime.datetime] = mapped_column(DateTime, server_default=func.now(), index=True)
